# Generated by Django 2.2.5 on 2019-09-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnfemaProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
                ('hidden', models.BooleanField()),
                ('identification', models.CharField(max_length=256)),
                ('span', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('sorting', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Meta')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AnfemaProjects')),
            ],
        ),
    ]
